export enum Icon8Group {
    People = 100,
    AnimalsAndInsects = 200,
    FoodAndDrinks = 300,
    Nature = 400,
    Sport = 500,
    TravelAndPlaces = 600,
    HouseAndHouseyard = 700,
    Body = 800,
    BeautyAndFashion = 900
}

export enum Icons8 {
    StandingMan = 100,
    Toilet = 101,
    Crowd = 102,
    Baby = 103,
    Father = 104,
    Family = 105,
    FatMan = 106,
    AmericanFootballPlayer = 107,
    Petanque = 108,
    Running = 109,
    Wheelchair = 110,
    Punching = 111,
    Attack = 112,
    Kicking = 113,
    Sup = 114,
    BalletDancerFemale = 115,
    HammerThrow = 116,
    SleepingInBed = 117,
    User = 118,
    StudentMale = 119,
    Supplier = 120,
    Worker = 121,
    Manager = 122,
    Artist = 123,
    Farmer = 124,
    Nurse = 125,
    PersonFemale = 126,
    SingerFemale = 127,
    Coughing = 128,
    Fever = 129,

    Cat = 200,
    GermanShepherd = 201,
    Bird = 202,
    ClownFish = 203,
    Chicken = 204,
    Duck = 205,
    Pig = 206,
    Rabbit = 207,
    Sheep = 208,
    Horse = 209,
    Cow = 210,
    Prawn = 211,
    Fox = 212,
    Frog = 213,
    Owl = 214,
    Parrot = 215,
    Elephant = 216,
    Turtle = 217,
    Starfish = 218,
    Octopus = 219,
    Dolphin = 220,
    Whale = 221,
    Penguin = 222,
    Bee = 223,
    Bug = 224,
    Spider = 225,
    Earthworm = 226,

    RiceBowl = 300,
    MisoSoup = 301,
    Salad = 302,
    Porridge = 303,
    Noodles = 304,
    Spaghetti = 305,
    Carrot = 306,
    Broccoli = 307,
    Lettuce = 308,
    Scallions = 309,
    Eggplant = 310,
    Tomato = 311,
    Potato = 312,
    Meat = 313,
    Thanksgiving = 314,
    Sausage = 315,
    SunnySideUpEggs = 316,
    Cheese = 317,
    Mushroom = 318,
    Nut = 319,
    Cherry = 320,
    Grapes = 321,
    Raspberry = 322,
    Strawberry = 323,
    Hamburger = 324,
    Sushi = 325,
    Pizza = 326,
    Brownie = 327,
    Cake = 328,
    ChocolateBar = 329,
    Cookies = 330,
    IceCreamCone = 331,
    BottleOfWater = 332,
    MilkBottle = 333,
    Cafe = 334,
    Cola = 335,
    WineBar = 336,
    Champagne = 337,
    Beer = 338,
    EnergyDrink = 339,

    Spring = 400,
    Summer = 401,
    Autumn = 402,
    Winter = 403,
    MoonAndStars = 404,
    Cloud = 405,
    PartlyCloudyDay = 406,
    Rain = 407,
    Storm = 408,
    Wind = 409,
    Snow = 410,
    Beach = 411,
    Forest = 412,
    OceanWave = 413,
    Cave = 414,
    Alps = 415,
    Valley = 416,
    Volcano = 417,
    Waterfall = 418,
    Iceberg = 419,

    Dumbell = 500,
    GymWeights = 501,
    SoccerBall = 502,
    FlappyDunk = 503,
    Volleyball = 504,
    BoxingGlove = 505,
    Shuttlecock = 506,
    PingPong = 507,
    SwimmingCap = 508,
    Hockey = 509,
    ArchersBow = 510,
    Ski = 511,

    Bicycle = 600,
    KickScooter = 601,
    Scooter = 602,
    Fiat = 603,
    ContainerTruck = 604,
    Bus = 605,
    Subway = 606,
    Airport = 607,
    WaterTransportation = 608,
    Bridge = 609,
    HotelRoom = 610,
    Map = 611,
    America = 612,
    Home = 613,
    Factory = 614,
    Manufacturing = 615,
    Company = 616,
    CityBuildings = 617,
    Skyscrapers = 618,
    Castle = 619,

    Sofa = 700,
    Bed = 701,
    Table = 702,
    Office = 703,
    Radio = 704,
    Hanger = 705,
    VacuumCleaner = 706,
    Aquarium = 707,
    AirConditioner = 708,
    WindowsClient = 709,
    Headphones = 710,
    Microphone = 711,
    Cooker = 712,
    Fridge = 713,
    Microwave = 714,
    Housekeeping = 715,
    Soap = 716,
    ToiletBowl = 717,
    Bath = 718,
    Shower = 719,
    Wardrobe = 720,
    WashingMachine = 721,
    EmptyTrash = 722,
    Garage = 723,
    LawnMower = 724,
    Drill = 725,
    GardenShears = 726,
    Hammer = 727,
    Spade = 728,
    SmallAxe = 729,
    OpenEndWrench = 730,
    Pitchfork = 731,
    Hacksaw = 732,
    Saw = 733,
    Screwdriver = 734,

    Erythrocytes = 800,
    Colon = 801,
    BodyCells = 802,
    Brain = 803,
    Lungs = 804,
    Torso = 805,
    HeartWithPulse = 806,
    Stomach = 807,
    Tooth = 808,
    Pill = 809,

    Mirror = 900,
    HairDryer = 901,
    Lipstick = 902,
    SpaMask = 903,
    Nails = 904,
    Umbrella = 905,
    StraightRazor = 906,
    Comb = 907,
    Barbershop = 908,
    Clothes = 909,
    Sweater = 910,
    MensPajama = 911,
    MensHoodie = 912,
    Raincoat = 913,
    Jacket = 914,
    Suit = 915,
    Coat = 916,
    LabCoat = 917,
    Kimono = 918,
}

export const icons8Names: {
    [id: number]: string
} = {
    [Icons8.StandingMan]: "standing-man",
    [Icons8.Toilet]: "toilet",
    [Icons8.Crowd]: "crowd",
    [Icons8.Baby]: "baby",
    [Icons8.Father]: "father",
    [Icons8.Family]: "family",
    [Icons8.FatMan]: "fat-man",
    [Icons8.AmericanFootballPlayer]: "american-football-player",
    [Icons8.Petanque]: "petanque",
    [Icons8.Running]: "running",
    [Icons8.Wheelchair]: "wheelchair",
    [Icons8.Punching]: "punching",
    [Icons8.Attack]: "attack",
    [Icons8.Kicking]: "kicking",
    [Icons8.Sup]: "sup",
    [Icons8.BalletDancerFemale]: "ballet-dancer-female",
    [Icons8.HammerThrow]: "hammer-throw",
    [Icons8.SleepingInBed]: "sleeping-in-bed",
    [Icons8.User]: "user",
    [Icons8.StudentMale]: "student-male",
    [Icons8.Supplier]: "supplier",
    [Icons8.Worker]: "worker",
    [Icons8.Manager]: "manager",
    [Icons8.Artist]: "artist",
    [Icons8.Farmer]: "farmer",
    [Icons8.Nurse]: "nurse",
    [Icons8.PersonFemale]: "person-female",
    [Icons8.SingerFemale]: "singer-female",
    [Icons8.Coughing]: "coughing",
    [Icons8.Fever]: "fever",

    [Icons8.Cat]: "cat",
    [Icons8.GermanShepherd]: "german-shepherd",
    [Icons8.Bird]: "bird",
    [Icons8.ClownFish]: "clown-fish",
    [Icons8.Chicken]: "chicken",
    [Icons8.Duck]: "duck",
    [Icons8.Pig]: "pig",
    [Icons8.Rabbit]: "rabbit",
    [Icons8.Sheep]: "sheep",
    [Icons8.Horse]: "horse",
    [Icons8.Cow]: "cow",
    [Icons8.Prawn]: "prawn",
    [Icons8.Fox]: "fox",
    [Icons8.Frog]: "frog",
    [Icons8.Owl]: "owl",
    [Icons8.Parrot]: "parrot",
    [Icons8.Elephant]: "elephant",
    [Icons8.Turtle]: "turtle",
    [Icons8.Starfish]: "starfish",
    [Icons8.Octopus]: "octopus",
    [Icons8.Dolphin]: "dolphin",
    [Icons8.Whale]: "whale",
    [Icons8.Penguin]: "penguin",
    [Icons8.Bee]: "bee",
    [Icons8.Bug]: "bug",
    [Icons8.Spider]: "spider",
    [Icons8.Earthworm]: "earthworm",

    [Icons8.RiceBowl]: "rice-bowl",
    [Icons8.MisoSoup]: "miso-soup",
    [Icons8.Salad]: "salad",
    [Icons8.Porridge]: "porridge",
    [Icons8.Noodles]: "noodles",
    [Icons8.Spaghetti]: "spaghetti",
    [Icons8.Carrot]: "carrot",
    [Icons8.Broccoli]: "broccoli",
    [Icons8.Lettuce]: "lettuce",
    [Icons8.Scallions]: "scallions",
    [Icons8.Eggplant]: "eggplant",
    [Icons8.Tomato]: "tomato",
    [Icons8.Potato]: "potato",
    [Icons8.Meat]: "meat",
    [Icons8.Thanksgiving]: "thanksgiving",
    [Icons8.Sausage]: "sausage",
    [Icons8.SunnySideUpEggs]: "sunny-side-up-eggs",
    [Icons8.Cheese]: "cheese",
    [Icons8.Mushroom]: "mushroom",
    [Icons8.Nut]: "nut",
    [Icons8.Cherry]: "cherry",
    [Icons8.Grapes]: "grapes",
    [Icons8.Raspberry]: "raspberry",
    [Icons8.Strawberry]: "strawberry",
    [Icons8.Hamburger]: "hamburger",
    [Icons8.Sushi]: "sushi",
    [Icons8.Pizza]: "pizza",
    [Icons8.Brownie]: "brownie",
    [Icons8.Cake]: "cake",
    [Icons8.ChocolateBar]: "chocolate-bar",
    [Icons8.Cookies]: "cookies",
    [Icons8.IceCreamCone]: "ice-cream-cone",
    [Icons8.BottleOfWater]: "bottle-of-water",
    [Icons8.MilkBottle]: "milk-bottle",
    [Icons8.Cafe]: "cafe",
    [Icons8.Cola]: "cola",
    [Icons8.WineBar]: "wine-bar",
    [Icons8.Champagne]: "champagne",
    [Icons8.Beer]: "beer",
    [Icons8.EnergyDrink]: "energy-drink",

    [Icons8.Spring]: "spring",
    [Icons8.Summer]: "summer",
    [Icons8.Autumn]: "autumn",
    [Icons8.Winter]: "winter",
    [Icons8.MoonAndStars]: "moon-and-stars",
    [Icons8.Cloud]: "cloud",
    [Icons8.PartlyCloudyDay]: "partly-cloudy-day",
    [Icons8.Rain]: "rain",
    [Icons8.Storm]: "storm",
    [Icons8.Wind]: "wind",
    [Icons8.Snow]: "snow",
    [Icons8.Beach]: "beach",
    [Icons8.Forest]: "forest",
    [Icons8.OceanWave]: "ocean-wave",
    [Icons8.Cave]: "cave",
    [Icons8.Alps]: "alps",
    [Icons8.Valley]: "valley",
    [Icons8.Volcano]: "volcano",
    [Icons8.Waterfall]: "waterfall",
    [Icons8.Iceberg]: "iceberg",

    [Icons8.Dumbell]: "dumbell",
    [Icons8.GymWeights]: "gym-weights",
    [Icons8.SoccerBall]: "soccer-ball",
    [Icons8.FlappyDunk]: "flappy-dunk",
    [Icons8.Volleyball]: "volleyball",
    [Icons8.BoxingGlove]: "boxing-glove",
    [Icons8.Shuttlecock]: "shuttlecock",
    [Icons8.PingPong]: "ping-pong",
    [Icons8.SwimmingCap]: "swimming-cap",
    [Icons8.Hockey]: "hockey",
    [Icons8.ArchersBow]: "archers-bow",
    [Icons8.Ski]: "ski",

    [Icons8.Bicycle]: "bicycle",
    [Icons8.KickScooter]: "kick-scooter",
    [Icons8.Scooter]: "scooter",
    [Icons8.Fiat]: "fiat-500",
    [Icons8.ContainerTruck]: "container-truck",
    [Icons8.Bus]: "bus",
    [Icons8.Subway]: "subway",
    [Icons8.Airport]: "airport",
    [Icons8.WaterTransportation]: "water-transportation",
    [Icons8.Bridge]: "bridge",
    [Icons8.HotelRoom]: "hotel-room",
    [Icons8.Map]: "map",
    [Icons8.America]: "america",
    [Icons8.Home]: "home",
    [Icons8.Factory]: "factory",
    [Icons8.Manufacturing]: "manufacturing",
    [Icons8.Company]: "company",
    [Icons8.CityBuildings]: "city-buildings",
    [Icons8.Skyscrapers]: "skyscrapers",
    [Icons8.Castle]: "castle",

    [Icons8.Sofa]: "sofa",
    [Icons8.Bed]: "bed",
    [Icons8.Table]: "table",
    [Icons8.Office]: "office",
    [Icons8.Radio]: "radio",
    [Icons8.Hanger]: "hanger",
    [Icons8.VacuumCleaner]: "vacuum-cleaner",
    [Icons8.Aquarium]: "aquarium",
    [Icons8.AirConditioner]: "air-conditioner",
    [Icons8.WindowsClient]: "windows-client",
    [Icons8.Headphones]: "headphones",
    [Icons8.Microphone]: "microphone",
    [Icons8.Cooker]: "cooker",
    [Icons8.Fridge]: "fridge",
    [Icons8.Microwave]: "microwave",
    [Icons8.Housekeeping]: "housekeeping",
    [Icons8.Soap]: "soap",
    [Icons8.ToiletBowl]: "toilet-bowl",
    [Icons8.Bath]: "bath",
    [Icons8.Shower]: "shower",
    [Icons8.Wardrobe]: "wardrobe",
    [Icons8.WashingMachine]: "washing-machine",
    [Icons8.EmptyTrash]: "empty-trash",
    [Icons8.Garage]: "garage",
    [Icons8.LawnMower]: "lawn-mower",
    [Icons8.Drill]: "drill",
    [Icons8.GardenShears]: "garden-shears",
    [Icons8.Hammer]: "hammer",
    [Icons8.Spade]: "spade",
    [Icons8.SmallAxe]: "small-axe",
    [Icons8.OpenEndWrench]: "open-end-wrench",
    [Icons8.Pitchfork]: "pitchfork",
    [Icons8.Hacksaw]: "hacksaw",
    [Icons8.Saw]: "saw",
    [Icons8.Screwdriver]: "screwdriver",

    [Icons8.Erythrocytes]: "erythrocytes",
    [Icons8.Colon]: "colon",
    [Icons8.BodyCells]: "body-cells",
    [Icons8.Brain]: "brain",
    [Icons8.Lungs]: "lungs",
    [Icons8.Torso]: "torso",
    [Icons8.HeartWithPulse]: "heart-with-pulse",
    [Icons8.Stomach]: "stomach",
    [Icons8.Tooth]: "tooth",
    [Icons8.Pill]: "pill",

    [Icons8.Mirror]: "mirror",
    [Icons8.HairDryer]: "hair-dryer",
    [Icons8.Lipstick]: "lipstick",
    [Icons8.SpaMask]: "spa-mask",
    [Icons8.Nails]: "nails",
    [Icons8.Umbrella]: "umbrella",
    [Icons8.StraightRazor]: "straight-razor",
    [Icons8.Comb]: "comb",
    [Icons8.Barbershop]: "barbershop",
    [Icons8.Clothes]: "clothes",
    [Icons8.Sweater]: "sweater",
    [Icons8.MensPajama]: "men's-pajama",
    [Icons8.MensHoodie]: "mens-hoodie",
    [Icons8.Raincoat]: "raincoat",
    [Icons8.Jacket]: "jacket",
    [Icons8.Suit]: "suit",
    [Icons8.Coat]: "coat",
    [Icons8.LabCoat]: "lab-coat",
    [Icons8.Kimono]: "kimono",
}